# Write it!

Platanus/NoCommand:
  Description: "Prefer usage of `ActiveJob` instead of `PowerTypes::Command`"
  Enabled: true
  Include:
    - "app/commands/**/*.rb"
  VersionAdded: "<<next>>"

Platanus/NoFlashInApi:
  Description: "Don't use `flash` in api controllers."
  Enabled: true
  SafeAutoCorrect: false
  Include:
    - "app/controllers/api/**/*.rb"
  VersionAdded: "<<next>>"

Platanus/NoEnumerize:
  Description: "Prefer usage of Rails `enum` instead of `Enumerize`"
  Enabled: true
  SafeAutoCorrect: false
  Include:
    - "app/models/**/*.rb"
  VersionAdded: "<<next>>"

Platanus/NoRenderJson:
  Description: "Prefer usage of `respond_with` instead of `render json:` to take advantage of `ApiResponder` and `serializers`"
  Enabled: true
  Include:
    - "app/controllers/**/*.rb"
  VersionAdded: "<<next>>"

Platanus/PunditInApplicationController:
  Description: "`Pundit` should be included only in the `Application Controller`"
  Enabled: true
  Include:
    - "app/controllers/**/*.rb"
  VersionAdded: "0.1.0"

Platanus/SingularSerializer:
  Description: "Serializers must be named with a singular resource name"
  Enabled: true
  Include:
    - "app/serializers/**/*.rb"
  VersionAdded: "<<next>>"
