# Write it!

Platanus/NoCommand:
  Description: "Prefer usage of `ActiveJob` instead of `PowerTypes::Command`"
  Enabled: true
  VersionAdded: "<<next>>"

Platanus/NoRenderJson:
  Description: "Prefer usage of `respond_with` instead of `render json:` to take advantage of `ApiResponder` and `serializers`"
  Enabled: true
  VersionAdded: "<<next>>"

Platanus/PunditInApplicationController:
  Description: "`Pundit` should be included only in the `Application Controller`"
  Enabled: true
  VersionAdded: "0.1.0"
